version: '3.2'

services:

  nginx:
    image: nginx:alpine
    container_name: lemp_nginx
    volumes:
      - ./ssl:/etc/ssl
      - ${WWW_DIR}:/var/www/html
      - ./log/nginx:/var/log/nginx
      - ./nginx/sites:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
      - 3000:443
    restart: always
    depends_on:
      - php
      - mysql
    links:
      - php

  php:
    image: calebfoster/php:7.1-fpm
    container_name: lemp_php
    restart: always
    expose:
      - 9000
    volumes:
      - ${WWW_DIR}:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./log/php:/var/log

  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lemp_phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=lemp_db
    restart: always
    depends_on:
      - mysql

  mysql:
    image: mariadb
    container_name: lemp_db
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 8989:3306
#    volumes:
#      - ./data/db/mysql:/var/lib/mysql